//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Travel.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Host
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Host()
        {
            this.HostAlbums = new HashSet<HostAlbum>();
            this.HostPictures = new HashSet<HostPicture>();
        }
    
        public int HostId { get; set; }
        public Nullable<int> TouristId { get; set; }
        public Nullable<int> HostingCountryId { get; set; }
        public Nullable<int> HostingCityId { get; set; }
        public string HostingPlaceAddress { get; set; }
        public string Rent { get; set; }
        public Nullable<System.DateTime> HostingStartTime { get; set; }
        public Nullable<System.DateTime> HostingStopTime { get; set; }
        public string HostingDetail { get; set; }
        public Nullable<bool> HostingStatus { get; set; }
        public Nullable<bool> HostAdminsPermit { get; set; }
        public Nullable<System.DateTime> HostDateOfAccountCreation { get; set; }
        public Nullable<int> HostProfilePicId { get; set; }
        public Nullable<int> HostTypeId { get; set; }
        public string HostingPhnNo { get; set; }
    
        public virtual City City { get; set; }
        public virtual Country Country { get; set; }
        public virtual HostPicture HostPicture { get; set; }
        public virtual HostType HostType { get; set; }
        public virtual Tourist Tourist { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HostAlbum> HostAlbums { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HostPicture> HostPictures { get; set; }
    }
}
