//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Travel.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class HostAlbum
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HostAlbum()
        {
            this.HostPictures = new HashSet<HostPicture>();
        }
    
        public int HostAlbumId { get; set; }
        public Nullable<int> HostId { get; set; }
        public Nullable<int> TouristId { get; set; }
        public Nullable<int> AlbumTypeId { get; set; }
        public Nullable<bool> HostAlbumPrivacy { get; set; }
        public Nullable<System.DateTime> HostAlbumDateOfAdded { get; set; }
        public Nullable<int> CountryId { get; set; }
        public Nullable<int> CityId { get; set; }
        public Nullable<int> PlaceId { get; set; }
        public Nullable<bool> HostAlbumAdminPermit { get; set; }
        public string HostAlbumName { get; set; }
    
        public virtual AlbumType AlbumType { get; set; }
        public virtual City City { get; set; }
        public virtual Country Country { get; set; }
        public virtual Host Host { get; set; }
        public virtual Place Place { get; set; }
        public virtual Tourist Tourist { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HostPicture> HostPictures { get; set; }
    }
}
