//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Travel.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class HostPicture
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HostPicture()
        {
            this.Hosts = new HashSet<Host>();
        }
    
        public int HostPictureId { get; set; }
        public Nullable<int> HostAlbumId { get; set; }
        public Nullable<int> HostId { get; set; }
        public Nullable<int> TouristId { get; set; }
        public byte[] HostPictureData { get; set; }
        public Nullable<int> AlbumTypeId { get; set; }
        public Nullable<System.DateTime> HostPictureDateOfAdded { get; set; }
        public Nullable<bool> HostPicturePrivacy { get; set; }
        public Nullable<bool> HostPictureAdminPermit { get; set; }
        public Nullable<int> PlaceId { get; set; }
        public Nullable<int> CountryId { get; set; }
        public int CityId { get; set; }
    
        public virtual AlbumType AlbumType { get; set; }
        public virtual City City { get; set; }
        public virtual Country Country { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Host> Hosts { get; set; }
        public virtual Host Host { get; set; }
        public virtual HostAlbum HostAlbum { get; set; }
        public virtual Place Place { get; set; }
        public virtual Tourist Tourist { get; set; }
    }
}
