//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Travel.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class OfferPicture
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OfferPicture()
        {
            this.Offers = new HashSet<Offer>();
        }
    
        public int OfferPictureId { get; set; }
        public Nullable<int> OfferAlbumId { get; set; }
        public Nullable<int> OfferId { get; set; }
        public Nullable<int> VendorId { get; set; }
        public byte[] OfferPictureData { get; set; }
        public Nullable<int> AlbumTypeId { get; set; }
        public Nullable<System.DateTime> OfferPictureDateOfAdded { get; set; }
        public Nullable<bool> OfferPicturePrivacy { get; set; }
        public Nullable<bool> OfferPictureAdminPermit { get; set; }
        public Nullable<int> CountryId { get; set; }
        public Nullable<int> CityId { get; set; }
        public Nullable<int> PlaceId { get; set; }
    
        public virtual AlbumType AlbumType { get; set; }
        public virtual City City { get; set; }
        public virtual Country Country { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Offer> Offers { get; set; }
        public virtual Offer Offer { get; set; }
        public virtual OfferAlbum OfferAlbum { get; set; }
        public virtual Place Place { get; set; }
        public virtual Vendor Vendor { get; set; }
    }
}
