//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Travel.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Offer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Offer()
        {
            this.OfferAlbums = new HashSet<OfferAlbum>();
            this.OfferPictures = new HashSet<OfferPicture>();
        }
    
        public int OfferId { get; set; }
        public string OfferName { get; set; }
        public Nullable<int> VendorId { get; set; }
        public Nullable<int> CountryId { get; set; }
        public Nullable<int> CityId { get; set; }
        public Nullable<int> OfferTypeId { get; set; }
        public string OfferPrice { get; set; }
        public string OfferDetail { get; set; }
        public Nullable<System.DateTime> OfferStartTime { get; set; }
        public Nullable<System.DateTime> OfferStopTime { get; set; }
        public Nullable<bool> OfferStatus { get; set; }
        public Nullable<bool> OfferAdminsPermit { get; set; }
        public Nullable<System.DateTime> OfferDateOfAccountCreation { get; set; }
        public Nullable<int> OfferProfilePicId { get; set; }
    
        public virtual City City { get; set; }
        public virtual Country Country { get; set; }
        public virtual OfferPicture OfferPicture { get; set; }
        public virtual OfferType OfferType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OfferAlbum> OfferAlbums { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OfferPicture> OfferPictures { get; set; }
    }
}
