//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Travel.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlaceAlbum
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PlaceAlbum()
        {
            this.PlacePictures = new HashSet<PlacePicture>();
        }
    
        public int PlaceAlbumId { get; set; }
        public string PlaceAlbumName { get; set; }
        public Nullable<int> PlaceId { get; set; }
        public Nullable<int> AlbumTypeId { get; set; }
        public Nullable<bool> PlaceAlbumAdminPermit { get; set; }
        public Nullable<System.DateTime> PlaceAlbumDateOfCreation { get; set; }
        public Nullable<int> CountryId { get; set; }
        public Nullable<int> CityId { get; set; }
        public Nullable<bool> PlaceAlbumPivacy { get; set; }
    
        public virtual AlbumType AlbumType { get; set; }
        public virtual City City { get; set; }
        public virtual Country Country { get; set; }
        public virtual Place Place { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlacePicture> PlacePictures { get; set; }
    }
}
