//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Travel.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlacePicture
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PlacePicture()
        {
            this.Places = new HashSet<Place>();
        }
    
        public int PlacePictureId { get; set; }
        public Nullable<int> PlaceId { get; set; }
        public Nullable<int> PlaceAlbumId { get; set; }
        public byte[] PlacePictureData { get; set; }
        public Nullable<int> AlbumTypeId { get; set; }
        public Nullable<System.DateTime> PlacePictureDateOfAdded { get; set; }
        public Nullable<bool> PlacePictureAdminPermit { get; set; }
        public Nullable<bool> PlacePicturePrivacy { get; set; }
        public Nullable<int> CountryId { get; set; }
        public Nullable<int> CityId { get; set; }
    
        public virtual AlbumType AlbumType { get; set; }
        public virtual City City { get; set; }
        public virtual Country Country { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Place> Places { get; set; }
        public virtual Place Place { get; set; }
        public virtual PlaceAlbum PlaceAlbum { get; set; }
    }
}
