//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Travel.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TouristPicture
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TouristPicture()
        {
            this.Tourists = new HashSet<Tourist>();
        }
    
        public int TouristPictureId { get; set; }
        public Nullable<int> TouristId { get; set; }
        public Nullable<int> TouristAlbumId { get; set; }
        public byte[] TouristPictureData { get; set; }
        public Nullable<int> AlbumTypeId { get; set; }
        public Nullable<System.DateTime> TouristPictureDateOfAdded { get; set; }
        public Nullable<bool> TouristPicturePrivarcy { get; set; }
        public Nullable<int> PlaceId { get; set; }
        public Nullable<bool> TouristPictureAdminPermit { get; set; }
        public Nullable<int> CountryId { get; set; }
        public Nullable<int> CityId { get; set; }
    
        public virtual AlbumType AlbumType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tourist> Tourists { get; set; }
        public virtual Tourist Tourist { get; set; }
        public virtual TouristAlbum TouristAlbum { get; set; }
    }
}
