//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Travel.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TouristAlbum
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TouristAlbum()
        {
            this.TouristPictures = new HashSet<TouristPicture>();
        }
    
        public int TouristAlbumId { get; set; }
        public string TouristAlbumName { get; set; }
        public Nullable<int> TouristId { get; set; }
        public Nullable<int> AlbumTypeId { get; set; }
        public Nullable<bool> TouristAlbumPrivacy { get; set; }
        public Nullable<System.DateTime> TouristAlbumDateOfCreated { get; set; }
        public Nullable<int> CountryId { get; set; }
        public Nullable<int> CityId { get; set; }
        public Nullable<int> PlaceId { get; set; }
        public Nullable<bool> TouristAlbumAdminPermit { get; set; }
    
        public virtual AlbumType AlbumType { get; set; }
        public virtual City City { get; set; }
        public virtual Country Country { get; set; }
        public virtual Place Place { get; set; }
        public virtual Tourist Tourist { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TouristPicture> TouristPictures { get; set; }
    }
}
