//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Travel.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tourist
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tourist()
        {
            this.CheckIns = new HashSet<CheckIn>();
            this.Hosts = new HashSet<Host>();
            this.HostAlbums = new HashSet<HostAlbum>();
            this.HostPictures = new HashSet<HostPicture>();
            this.TouristAlbums = new HashSet<TouristAlbum>();
            this.TouristPictures = new HashSet<TouristPicture>();
            this.WishLists = new HashSet<WishList>();
        }
    
        public int TouristId { get; set; }
        public string TouristName { get; set; }
        public string TouristEmail { get; set; }
        public Nullable<int> CountryId { get; set; }
        public int CityId { get; set; }
        public string TouristPhnNo { get; set; }
        public string TouristAddress { get; set; }
        public string TouristEmergencyPhnNo { get; set; }
        public Nullable<bool> TouristsStatus { get; set; }
        public Nullable<bool> TouristsHostStatus { get; set; }
        public Nullable<bool> TouristAdminsPermit { get; set; }
        public Nullable<System.DateTime> TouristDateOfAccountCreation { get; set; }
        public string TouristPassword { get; set; }
        public Nullable<int> TouristProfilePicId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CheckIn> CheckIns { get; set; }
        public virtual City City { get; set; }
        public virtual Country Country { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Host> Hosts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HostAlbum> HostAlbums { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HostPicture> HostPictures { get; set; }
        public virtual TouristPicture TouristPicture { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TouristAlbum> TouristAlbums { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TouristPicture> TouristPictures { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WishList> WishLists { get; set; }
    }
}
