//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Travel.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vendor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vendor()
        {
            this.CheckIns = new HashSet<CheckIn>();
            this.OfferAlbums = new HashSet<OfferAlbum>();
            this.OfferPictures = new HashSet<OfferPicture>();
            this.VendorAlbums = new HashSet<VendorAlbum>();
            this.VendorPictures = new HashSet<VendorPicture>();
        }
    
        public int VendorId { get; set; }
        public string VendorName { get; set; }
        public Nullable<int> VendorTypeId { get; set; }
        public string VendorEmail { get; set; }
        public string VendorPhnNo { get; set; }
        public string VendorAddress { get; set; }
        public string VendorOfficeName { get; set; }
        public Nullable<int> CountryId { get; set; }
        public Nullable<int> CityId { get; set; }
        public string VendorOfficePhnNo { get; set; }
        public string VendorOfficeAddress { get; set; }
        public string VendorOfficeWebsite { get; set; }
        public string VendorsVendorShipDetail { get; set; }
        public Nullable<bool> VendorsStatus { get; set; }
        public Nullable<bool> VendorOfferStatus { get; set; }
        public Nullable<bool> VendorAdminsPermit { get; set; }
        public Nullable<System.DateTime> VendorDateOfAccountCreation { get; set; }
        public string VendorPassword { get; set; }
        public Nullable<int> VendorFavourite { get; set; }
        public Nullable<int> VendorProfilePicId { get; set; }
        public string VendorOfficeMail { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CheckIn> CheckIns { get; set; }
        public virtual City City { get; set; }
        public virtual Country Country { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OfferAlbum> OfferAlbums { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OfferPicture> OfferPictures { get; set; }
        public virtual VendorPicture VendorPicture { get; set; }
        public virtual VendorType VendorType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VendorAlbum> VendorAlbums { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VendorPicture> VendorPictures { get; set; }
    }
}
