//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Travel.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class VendorPicture
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VendorPicture()
        {
            this.Vendors = new HashSet<Vendor>();
        }
    
        public int VendorPictureId { get; set; }
        public int VendorId { get; set; }
        public int VendorAlbumId { get; set; }
        public byte[] VendorPictureData { get; set; }
        public Nullable<int> AlbumTypeId { get; set; }
        public Nullable<System.DateTime> VendorPictureDateOfAdded { get; set; }
        public Nullable<bool> VendorPicturePrivacy { get; set; }
        public Nullable<bool> VendorPictureAdminPermit { get; set; }
        public Nullable<int> CountryId { get; set; }
        public Nullable<int> CityId { get; set; }
        public Nullable<int> PlaceId { get; set; }
    
        public virtual AlbumType AlbumType { get; set; }
        public virtual City City { get; set; }
        public virtual Country Country { get; set; }
        public virtual Place Place { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vendor> Vendors { get; set; }
        public virtual Vendor Vendor { get; set; }
        public virtual VendorAlbum VendorAlbum { get; set; }
    }
}
