//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Travel.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class WishList
    {
        public int WishlistId { get; set; }
        public int TouristId { get; set; }
        public Nullable<int> CountryId { get; set; }
        public Nullable<int> CityId { get; set; }
        public Nullable<int> PlaceId { get; set; }
        public Nullable<System.DateTime> WishAddedDate { get; set; }
        public Nullable<int> VendorId { get; set; }
    
        public virtual City City { get; set; }
        public virtual Country Country { get; set; }
        public virtual Place Place { get; set; }
        public virtual Tourist Tourist { get; set; }
    }
}
